# ---------- Base ----------
FROM node:20-slim AS base
WORKDIR /backend
COPY package.json package-lock.json ./

# ---------- Development ----------
FROM base AS development
RUN npm ci
COPY . .
RUN npx prisma generate
EXPOSE 3000
CMD ["npm", "run", "start:dev"]

# ---------- Build ----------
FROM base AS build
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

# ---------- Production ----------
FROM node:20-slim AS production
WORKDIR /backend
ENV NODE_ENV=production
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --from=build /backend/dist ./dist
COPY --from=build /backend/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /backend/prisma ./prisma
EXPOSE 3000
CMD ["node", "dist/main"]


# # Use Node.js 20 as the base image (required by NestJS 11 / Node 20+ deps)
# FROM node:20

