version: '3.8'

services:
  postgres_test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stoneshop_test
    ports:
      - '5433:5432'
