export const ErrorCode = {
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CODE_EXPIRED: "CODE_EXPIRED",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN: "UNKNOWN",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
